[package]
name = "xlog"
version = "0.3.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "local-time",
    "time",
] }
thiserror = "2.0"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[features]
default = ["json"]
json = ["dep:serde", "dep:serde_json", "tracing-subscriber/json"]

[dev-dependencies]
tempfile = "3.0"
